apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-deployment
  labels:
    app: green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: green
  template:
    metadata:
      labels:
        app: green
    spec:
      containers:
      - name: nginx
        image: nginx

        command:
        - /bin/sh
        - -c
        - |
          echo "Welcome to Green New APP" > /usr/share/nginx/html/index.html
          nginx -g 'daemon off;'

        ports:
        - containerPort: 80

