apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - blue-deployment.yaml
  - blue-service.yaml
  - green-deplyment.yaml
  - green-service.yaml
  - gateway.yaml
  - httproute.yaml